### PR TITLE
Add BSD 2-Clause license

### PR DESCRIPTION
**Pull request by jletey**
Since we already have 3-Clause, we mine as well also have the 2-Clause. I find them both useful!

### CODE REVIEW

**Comment by nikivdev** [comment]
Perfect

**Comment by nikivdev** [comment]
On second thought, shouldn't it be `bsd3` for the other one as argument now?

**Comment by nikivdev** [comment]
@johnletey can maybe look into changing `bsd` to `bsd3` with #9 PR :)

Unless you left it to `bsd` on purpose. I am not too familiar with this license.

**Comment by jletey** [comment]
Sorry ... didn't see this until after I submitted #16 

If you go to [OSS Ninja](https://oss.ninja), they have the BSD 3-Clause listed under BSD. Honestly, I'm not quite sure.

IMHO I'd say that we switch it to `bsd3` (since that's more intuitive to my brain) ... and if any users have complaints about it, we can change it back

**Comment by nikivdev** [comment]
I agree. If anything user can alias it to `bsd` if he/she likes.

**Comment by nikivdev** [comment]
You going to open a new PR for it? You can commit to #16 if you wish

**Comment by jletey** [comment]
Honestly, I like having different pull requests for different things

I'll create a new pull request ... shouldn't take that long

**Pull request merged**
