### PR TITLE
Completely redesign the codebase

### PR DESCRIPTION
**Pull request by jletey**
@nikitavoloboev Here's a big update to the codebase that simplifies adding new licenses. Really looking forward to what you think about it 😄!

There is one problem ... you can't run it outside of the source directory (because all of the licenses are created from templates). This shouldn't be that bad to fix ... we can download them from the GitHub url of the license templates

### CODE REVIEW

**Comment by nikivdev** [comment]
This seems like a nice change. I like the idea of templates.

I can't merge this though as the command doesn't work as it stands.

Can we keep the templates and everything inside the command itself?

**Comment by jletey** [comment]
> Can we keep the templates and everything inside the command itself?

Possibly ... but that would be hard because then we run into the same problem that we're trying to get rid of (having to convert the file into a string with newline characters, indentations, and correct quotations)

**Comment by nikivdev** [comment]
So how do you propose we solve this issue of command working out of the box for users?

I saw you star some node.js license creator that also used templates. Maybe we can use that approach?

**Comment by jletey** [comment]
> I saw you star some node.js license creator that also used templates. Maybe we can use that approach?

Yes ... I've been drawing ideas from her tool ... the way she implements it is she pulls the licenses from the GitHub API. We could also do this ... what do you think?

**Comment by jletey** [comment]
@nikitavoloboev This PR hasn't made any progress ... so I'm closing it. I'll definitely make sure to revisit later though!

**Pull request closed without merging**
