### PR TITLE
Regenerate license

### PR DESCRIPTION
**Pull request by jletey**
@nikitavoloboev I was noticing that GitHub wasn't recognising the license, so I regenerated it to fix it. I also fixed some whitespace errors with the MIT license.

### CODE REVIEW

**Comment by nikivdev** [comment]
Strange. I wonder why it wasn't recognizing it.

**Comment by nikivdev** [comment]
It's still not recognizing it. I checked my other repos and they're all fine.

**Comment by jletey** [comment]
> It's still not recognizing it. I checked my other repos and they're all fine.

@nikitavoloboev Just noticed that too ... this is very strange

shot 2019-02-25 at 19 59 39

**Comment by nikivdev** [comment]
Probably a GitHub bug..

**Comment by jletey** [comment]
Probably

**Pull request merged**
