### PR TITLE
Add `--md` flag

### PR DESCRIPTION
**Pull request by jletey**
@nikitavoloboev @michaelmior Here you guys go!

### CODE REVIEW

**Comment by michaelmior** [comment]
Amazing! Thanks @johnletey :)

**Comment by jletey** [comment]
@michaelmior No problem ... my pleasure!

**Comment by michaelmior** [comment]
Although as a side note, it would be nice in the future if `LICENSE.md` could actually use Markdown formatting. For example, I use the [markdown-licenses](https://github.com/IQAndreas/markdown-licenses) repo.

**Comment by jletey** [comment]
@michaelmior Will definitely keep it in mind ... actually, if you want to open another issue I can start playing around with the idea

**Comment by nikivdev** [comment]
Looks good

**Comment by jletey** [comment]
@michaelmior I was thinking about using license templates for automation (#19) ... so this is definitely an option (and [markdown-licenses](
https://github.com/IQAndreas/markdown-licenses) will most likely be very handy)!

@nikitavoloboev Wonderful!

**Comment by jletey** [comment]
@michaelmior I opened an issue for you: #36

**Pull request merged**
